name: Build and Push Docker image

on:
  push:
    branches:

main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

name: Checkout code
    uses: actions/checkout@v4


name: Log in to Docker Hub
    run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


name: Build Docker image
    run: docker build -t nestor1/my-php-apache-app:latest .


name: Push Docker image
    run: docker push nestor1/my-php-apache-app:latest
